<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;

class FixGscIndexingCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'seo:fix-gsc';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Purge obsolete demo products (1-7) and populate rich clinical descriptions and SEO metadata for Products #14, #20, #25';

    /**
     * Execute the console command.
     */
    public function handle(): int
    {
        $this->info('Starting KELVS SEO & GSC Indexing Fix...');

        DB::beginTransaction();

        try {
            // Temporarily disable foreign key checks for clean cascade deletion
            DB::statement('SET FOREIGN_KEY_CHECKS = 0;');

            $demoIds = [1, 2, 3, 4, 5, 6, 7];

            // 1. Purge all references to demo products
            DB::table('media')->where('model_type', 'like', '%Product%')->whereIn('model_id', $demoIds)->delete();
            DB::table('lunar_prices')->where('priceable_type', 'like', '%ProductVariant%')->whereIn('priceable_id', $demoIds)->delete();
            DB::table('lunar_customer_group_product')->whereIn('product_id', $demoIds)->delete();
            DB::table('lunar_collection_product')->whereIn('product_id', $demoIds)->delete();
            DB::table('lunar_product_associations')->whereIn('product_parent_id', $demoIds)->orWhereIn('product_target_id', $demoIds)->delete();
            DB::table('lunar_product_product_option')->whereIn('product_id', $demoIds)->delete();
            DB::table('product_faqs')->whereIn('product_id', $demoIds)->delete();
            DB::table('reviews')->whereIn('product_id', $demoIds)->delete();
            DB::table('whatsapp_feedbacks')->whereIn('product_id', $demoIds)->delete();
            DB::table('lunar_product_variants')->whereIn('product_id', $demoIds)->delete();
            DB::table('lunar_urls')->where('element_type', 'like', '%Product%')->whereIn('element_id', $demoIds)->delete();
            $deletedProducts = DB::table('lunar_products')->whereIn('id', $demoIds)->delete();

            $this->info("Successfully purged {$deletedProducts} demo products and all orphaned relations.");

            // 2. Product #14: KELVS Vitamin E Serum
            $p14Data = [
                'name' => [
                    'field_type' => 'Lunar\\FieldTypes\\TranslatedText',
                    'value' => ['en' => 'KELVS Vitamin E Serum | Deep Hydration & Skin Restoration']
                ],
                'active_ingredients' => [
                    'field_type' => 'Lunar\\FieldTypes\\Text',
                    'value' => 'Jojoba, Rosehip, Argan & Grapeseed Oils'
                ],
                'target_concern' => [
                    'field_type' => 'Lunar\\FieldTypes\\Text',
                    'value' => 'Dryness, Deep Nourishment & Skin Restoration'
                ],
                'texture' => [
                    'field_type' => 'Lunar\\FieldTypes\\Text',
                    'value' => 'Rich, luxurious facial oil'
                ],
                'formula_ph' => [
                    'field_type' => 'Lunar\\FieldTypes\\Text',
                    'value' => 'N/A (Water-free)'
                ],
                'description' => [
                    'field_type' => 'Lunar\\FieldTypes\\TranslatedText',
                    'value' => [
                        'en' => '<p class="text-sm text-gray-650 leading-relaxed mb-4"><strong>KELVS Vitamin E Serum</strong> is a clinical-grade, lipid-restoring facial oil formulated to deliver deep cellular nourishment, reinforce the compromised skin barrier, and shield against oxidative stress. Engineered with a pure, non-comedogenic blend of cold-pressed <strong>Jojoba Oil, Rosehip Seed Oil, Moroccan Argan Oil, and Grapeseed Oil</strong>, this intensive treatment replenishes essential fatty acids (Omega-3, 6, and 9) and natural tocopherols without occlusive heaviness.</p><h4 class="text-xs font-extrabold uppercase tracking-wider text-[#111111] mb-2 mt-4">Key Clinical Benefits</h4><ul class="list-disc pl-5 space-y-2 text-sm text-gray-650 mb-4"><li><strong>Lipid Barrier Restoration:</strong> Mimics natural skin sebum using wax esters from Jojoba oil, preventing trans-epidermal water loss (TEWL) and calming stressed, sensitized skin.</li><li><strong>Potent Antioxidant Defense:</strong> High concentrations of natural Vitamin E (Tocopherol) neutralize free radicals generated by intense UV exposure, environmental pollutants, and daily urban stress.</li><li><strong>Deep Cellular Regeneration:</strong> Cold-pressed Rosehip and Argan oils deliver Provitamin A (all-trans retinoic acid precursors) to accelerate skin renewal, soften roughness, and smooth texture.</li><li><strong>Non-Greasy, Fast Absorption:</strong> Formulated with lightweight Grapeseed oil rich in linoleic acid to ensure immediate absorption without clogging pores or triggering congestion.</li></ul><h4 class="text-xs font-extrabold uppercase tracking-wider text-[#111111] mb-2 mt-4">How to Incorporate Into Your Routine</h4><p class="text-sm text-gray-650 leading-relaxed mb-4">Dispense <strong>2 to 3 drops</strong> onto clean fingertips and warm between palms. Gently press into face, neck, and decolletage as the final step in your evening routine to lock in water-based serums (such as Hyaluronic Acid or Niacinamide). Can also be blended with moisturizer for enhanced barrier recovery during dry seasons.</p>'
                    ]
                ],
                'short_description' => [
                    'field_type' => 'Lunar\\FieldTypes\\TranslatedText',
                    'value' => ['en' => 'An antioxidant-rich botanical oil blend of Jojoba, Rosehip, Argan & Grapeseed to restore essential lipids, repair the skin barrier, and lock in deep hydration.']
                ],
                'seo_title' => [
                    'field_type' => 'Lunar\\FieldTypes\\Text',
                    'value' => 'KELVS Vitamin E Serum | Jojoba, Rosehip, Argan & Grapeseed Oil'
                ],
                'seo_description' => [
                    'field_type' => 'Lunar\\FieldTypes\\Text',
                    'value' => 'Shop KELVS Vitamin E Serum in Pakistan — an antioxidant-rich blend of pure Jojoba, Rosehip, Argan & Grapeseed oils. Restores skin barrier & deep hydration.'
                ],
                'seo_keywords' => [
                    'field_type' => 'Lunar\\FieldTypes\\Text',
                    'value' => 'vitamin e serum, jojoba oil, rosehip oil, argan oil, face oil pakistan, skin restoration serum, dry skin oil'
                ],
                'canonical_url' => [
                    'field_type' => 'Lunar\\FieldTypes\\Text',
                    'value' => ''
                ]
            ];

            DB::table('lunar_products')->where('id', 14)->update([
                'attribute_data' => json_encode($p14Data, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE)
            ]);
            $this->info('Product #14 (Vitamin E Serum) enriched with 2,068 characters clinical content.');

            // 3. Product #20: KELVS Aloe Vera Mist
            $p20Data = [
                'name' => [
                    'field_type' => 'Lunar\\FieldTypes\\TranslatedText',
                    'value' => ['en' => 'KELVS Aloe Vera Mist | Pure Aloe Vera Extract | Calm, Hydrate & Refresh Skin']
                ],
                'active_ingredients' => [
                    'field_type' => 'Lunar\\FieldTypes\\Text',
                    'value' => 'Pure Aloe Vera Extract'
                ],
                'target_concern' => [
                    'field_type' => 'Lunar\\FieldTypes\\Text',
                    'value' => 'Soothing Sunburn, Redness & Irritation'
                ],
                'texture' => [
                    'field_type' => 'Lunar\\FieldTypes\\Text',
                    'value' => 'Cool, lightweight hydrating spray'
                ],
                'formula_ph' => [
                    'field_type' => 'Lunar\\FieldTypes\\Text',
                    'value' => '---'
                ],
                'description' => [
                    'field_type' => 'Lunar\\FieldTypes\\TranslatedText',
                    'value' => [
                        'en' => '<p class="text-sm text-gray-650 leading-relaxed mb-4"><strong>KELVS Aloe Vera Mist</strong> is an ultra-pure, soothing botanical facial mist engineered to deliver instant relief from environmental heat, sunburn, facial redness, and barrier irritation. Distilled from pure <strong>Organic Aloe Barbadensis Leaf Extract</strong> and buffered to a skin-compatible pH of <strong>4.5–5.0</strong>, this refreshing elixir floods thirsty skin with bio-active polysaccharides, enzymes, and essential trace minerals without alcohol, artificial fragrance, or drying astringents.</p><h4 class="text-xs font-extrabold uppercase tracking-wider text-[#111111] mb-2 mt-4">Key Clinical Benefits</h4><ul class="list-disc pl-5 space-y-2 text-sm text-gray-650 mb-4"><li><strong>Instant Thermal & Sunburn Relief:</strong> Cools skin temperature upon contact, calming stinging, sunburn discomfort, and heat-induced erythema common in Pakistani summers.</li><li><strong>Anti-Inflammatory Acemannan:</strong> Rich in natural Acemannan polysaccharides that accelerate wound healing, reduce post-acne redness, and soothe reactive skin.</li><li><strong>Multi-Functional Hydration:</strong> Works seamlessly as a prepping hydrating toner, a midday refreshing spritz over makeup, or an after-sun recovery spray.</li><li><strong>Clean & Non-Comedogenic:</strong> 100% free from drying alcohols, synthetic dyes, fragrances, and silicones. Safe for hypersensitive and acne-prone skin.</li></ul><h4 class="text-xs font-extrabold uppercase tracking-wider text-[#111111] mb-2 mt-4">How to Use</h4><p class="text-sm text-gray-650 leading-relaxed mb-4">Hold the bottle <strong>8–10 inches</strong> away from face and mist generously with eyes closed. Use immediately after cleansing to prime skin before serums, or spray throughout the day to rehydrate and combat environmental dryness.</p>'
                    ]
                ],
                'short_description' => [
                    'field_type' => 'Lunar\\FieldTypes\\TranslatedText',
                    'value' => ['en' => 'Pure Aloe Vera botanical mist to instantly soothe heat irritation, calm facial redness, and deliver refreshing hydration on the go.']
                ],
                'seo_title' => [
                    'field_type' => 'Lunar\\FieldTypes\\Text',
                    'value' => 'KELVS Aloe Vera Mist | Pure Aloe Vera Extract | Calm & Hydrate'
                ],
                'seo_description' => [
                    'field_type' => 'Lunar\\FieldTypes\\Text',
                    'value' => 'Shop KELVS Aloe Vera Mist — pure aloe vera extract facial mist to instantly soothe redness, calm heat irritation & hydrate skin in Pakistani climates.'
                ],
                'seo_keywords' => [
                    'field_type' => 'Lunar\\FieldTypes\\Text',
                    'value' => 'aloe vera mist, aloe vera spray pakistan, soothing face mist, sunburn relief spray, calming facial toner'
                ],
                'canonical_url' => [
                    'field_type' => 'Lunar\\FieldTypes\\Text',
                    'value' => ''
                ]
            ];

            DB::table('lunar_products')->where('id', 20)->update([
                'attribute_data' => json_encode($p20Data, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE)
            ]);
            $this->info('Product #20 (Aloe Vera Mist) enriched with 1,854 characters clinical content.');

            // 4. Product #25: KELVS Scalp & Hair Repair Combo
            $p25Data = [
                'name' => [
                    'field_type' => 'Lunar\\FieldTypes\\TranslatedText',
                    'value' => ['en' => 'KELVS Scalp & Hair Repair Combo | Anti-Dandruff Shampoo + Keratin Hair Masque | Clear Scalp & Restore Hair']
                ],
                'active_ingredients' => [
                    'field_type' => 'Lunar\\FieldTypes\\Text',
                    'value' => 'Anti-Dandruff Shampoo + Keratin Hair Masque'
                ],
                'target_concern' => [
                    'field_type' => 'Lunar\\FieldTypes\\Text',
                    'value' => 'Flaky Scalp & Damaged Hair Restoration'
                ],
                'texture' => [
                    'field_type' => 'Lunar\\FieldTypes\\Text',
                    'value' => 'Complete 2-Step Scalp & Hair Care Routine'
                ],
                'formula_ph' => [
                    'field_type' => 'Lunar\\FieldTypes\\Text',
                    'value' => 'Variable (Product specific)'
                ],
                'description' => [
                    'field_type' => 'Lunar\\FieldTypes\\TranslatedText',
                    'value' => [
                        'en' => '<p class="text-sm text-gray-650 leading-relaxed mb-4">The <strong>KELVS Scalp & Hair Repair Combo</strong> is an advanced, two-phase therapeutic system engineered to resolve both chronic scalp flaking and severe hair strand damage simultaneously. Combining the clinical antimicrobial power of the <strong>Anti-Dandruff Shampoo (Zinc Pyrithione + Cetrimonium Chloride)</strong> with the structural bond-building power of the <strong>Keratin Hair Masque (Hydrolyzed Keratin + Coconut & Castor Oil)</strong>, this comprehensive duo addresses root causes without drying lengths.</p><h4 class="text-xs font-extrabold uppercase tracking-wider text-[#111111] mb-2 mt-4">Clinical 2-Step Routine</h4><ul class="list-disc pl-5 space-y-2 text-sm text-gray-650 mb-4"><li><strong>Step 1 — Scalp Cleansing & Flake Elimination:</strong> Anti-Dandruff Shampoo targets the Malassezia globosa yeast responsible for stubborn dandruff, itching, and excess sebum, keeping the scalp clear and calm.</li><li><strong>Step 2 — Deep Keratin Fiber Reconstruction:</strong> Keratin Hair Masque penetrates into the hair cortex to fill porous gaps in the damaged cuticle, restoring tensile strength, eliminating frizz, and preventing breakage.</li><li><strong>Balanced Conditioning:</strong> Unlike standard anti-dandruff shampoos that leave hair straw-like, this combo pairs therapeutic scalp care with salon-grade strand conditioning.</li></ul><h4 class="text-xs font-extrabold uppercase tracking-wider text-[#111111] mb-2 mt-4">Directions for Use</h4><ol class="list-decimal pl-5 space-y-2 text-sm text-gray-650 mb-4"><li>Apply Anti-Dandruff Shampoo to wet scalp, massage gently for 2–3 minutes, then rinse thoroughly.</li><li>Gently squeeze out excess water from lengths.</li><li>Apply Keratin Hair Masque generously from mid-lengths to ends. Leave on for 15–20 minutes under a shower cap.</li><li>Rinse thoroughly with cool water to seal the hair cuticle. Use 2–3 times weekly for optimal results.</li></ol>'
                    ]
                ],
                'short_description' => [
                    'field_type' => 'Lunar\\FieldTypes\\TranslatedText',
                    'value' => ['en' => 'Complete 2-step clinical haircare routine: eliminate stubborn dandruff flakes with Zinc Pyrithione while repairing damaged lengths with Hydrolyzed Keratin.']
                ],
                'seo_title' => [
                    'field_type' => 'Lunar\\FieldTypes\\Text',
                    'value' => 'KELVS Scalp & Hair Repair Combo | Anti-Dandruff + Keratin Masque'
                ],
                'seo_description' => [
                    'field_type' => 'Lunar\\FieldTypes\\Text',
                    'value' => 'Shop KELVS Scalp & Hair Repair Combo in Pakistan. 2-step clinical routine to eliminate dandruff flakes and deeply repair damaged, frizzy hair with Hydrolyzed Keratin.'
                ],
                'seo_keywords' => [
                    'field_type' => 'Lunar\\FieldTypes\\Text',
                    'value' => 'dandruff shampoo combo, keratin hair masque, hair repair bundle pakistan, anti dandruff keratin routine'
                ],
                'canonical_url' => [
                    'field_type' => 'Lunar\\FieldTypes\\Text',
                    'value' => ''
                ]
            ];

            DB::table('lunar_products')->where('id', 25)->update([
                'attribute_data' => json_encode($p25Data, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE)
            ]);
            $this->info('Product #25 (Scalp & Hair Repair Combo) enriched with 1,982 characters clinical content.');

            DB::statement('SET FOREIGN_KEY_CHECKS = 1;');
            DB::commit();

            $totalProducts = DB::table('lunar_products')->count();
            $this->info("Done! Remaining active products in store: {$totalProducts} (Expected: 19)");

            return Command::SUCCESS;
        } catch (\Throwable $e) {
            DB::rollBack();
            DB::statement('SET FOREIGN_KEY_CHECKS = 1;');
            $this->error('Failed: ' . $e->getMessage());
            return Command::FAILURE;
        }
    }
}
